"""Generate a PNG image from a text prompt using fal.ai image generation."""

from pathlib import Path

import weave
import fal_client
import os
import httpx


@weave.op()
def generate_image(prompt: str, output_path: str | Path) -> Path:
    """Generate a single image and save it to output_path."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # fal-client reads credentials from env (FAL_KEY or FAL_KEY_ID/FAL_KEY_SECRET)
    if not (os.getenv("FAL_KEY") or (os.getenv("FAL_KEY_ID") and os.getenv("FAL_KEY_SECRET"))):
        raise RuntimeError("No credentials found. Set FAL_KEY (recommended).")

    # Use fal.ai nano-banana-2 model
    result = fal_client.run(
        "fal-ai/nano-banana-2",
        arguments={
            "prompt": prompt,
            "num_images": 1,
            "image_size": "square_hd",  # 1024x1024
            "enable_safety_checker": True,
        },
    )

    # fal returns image URLs, download and save
    images = result.get("images") or []
    if not images:
        raise RuntimeError("No image generated by fal.ai")

    image_url = images[0]["url"]

    resp = httpx.get(image_url, timeout=60)
    resp.raise_for_status()
    output_path.write_bytes(resp.content)

    print(f"  ✓ Saved image → {output_path}")
    return output_path